# Render Blueprint for POS Backend
# Docs: https://render.com/docs/yaml-spec

services:
  - type: web
    name: junior-joy-pos-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false # Set in Render dashboard for security
      - key: JWT_SECRET
        sync: false # Set in Render dashboard for security
      - key: PORT
        value: 5000
