# Render Blueprint for POS Backend
# Docs: https://render.com/docs/yaml-spec

services:
  - type: web
    name: junior-joy-pos-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Rettey:Adhu1447@cluster0.qi38xbl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: junior_joy_pos_secret_key
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
